name: Deploy FastAPI to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t haico99/fastapi-app:latest .
          docker push haico99/fastapi-app:latest

      - name: SSH into VPS & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            kubectl apply -f /root/k3s-fastapi/deployment.yaml
            kubectl apply -f /root/k3s-fastapi/service.yaml
            kubectl rollout restart deployment fastapi-app
